"""Add Comment

Revision ID: 45de30c2318f
Revises: 59d5863cdee0
Create Date: 2026-01-23 15:28:44.809632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45de30c2318f'
down_revision = '59d5863cdee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
