"""Add User

Revision ID: 937b031a3d01
Revises: 45de30c2318f
Create Date: 2026-02-20 13:55:14.948173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937b031a3d01'
down_revision = '45de30c2318f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
